from __future__ import annotations

import operator

import torch
import torch.nn.functional as F

from codegen_backend.ops_registry import _OpRegistry
from codegen_backend.registry import _TargetInfo, build_target_registry as _base_target_registry
from codegen_backend.specs import OpKind, _OpSpec


def build_supported_ops() -> dict[str, _OpSpec]:
    registry = _OpRegistry()

    registry.register_binary("add", symbol="+").targets(
        operator.add,
        torch.add,
        torch.ops.prims.add,
        torch.ops.prims.add.default,
        torch.ops.aten.add.Tensor,
        torch.ops.aten.add.Scalar,
        torch.ops.aten.add_.Tensor,
        torch.ops.aten.add_,
    ).inplace(
        torch.ops.aten.add_.Tensor,
        torch.ops.aten.add_,
    ).build()
    registry.register_unary("_to_copy").targets(
        torch.ops.aten._to_copy,
        torch.ops.aten._to_copy.default,
    ).build()
    registry.register_binary("sub", symbol="-").targets(
        operator.sub,
        torch.sub,
        torch.ops.prims.sub,
        torch.ops.prims.sub.default,
        torch.ops.aten.sub.Tensor,
        torch.ops.aten.sub.Scalar,
        torch.ops.aten.sub_.Tensor,
        torch.ops.aten.sub_,
    ).inplace(
        torch.ops.aten.sub_.Tensor,
        torch.ops.aten.sub_,
    ).build()
    registry.register_binary("mul", symbol="*").targets(
        operator.mul,
        torch.mul,
        torch.ops.prims.mul,
        torch.ops.prims.mul.default,
        torch.ops.aten.mul.Tensor,
        torch.ops.aten.mul.Scalar,
        torch.ops.aten.mul_.Tensor,
        torch.ops.aten.mul_,
    ).inplace(
        torch.ops.aten.mul_.Tensor,
        torch.ops.aten.mul_,
    ).build()
    registry.register_binary("bitwise_and").targets(
        operator.and_,
        torch.bitwise_and,
        torch.ops.aten.bitwise_and.Tensor,
        torch.ops.aten.bitwise_and.Scalar,
        torch.ops.aten.bitwise_and_.Tensor,
        torch.ops.aten.bitwise_and_,
        torch.ops.aten.bitwise_and,
    ).inplace(
        torch.ops.aten.bitwise_and_.Tensor,
        torch.ops.aten.bitwise_and_,
    ).build()
    registry.register_binary("bitwise_or").targets(
        operator.or_,
        torch.bitwise_or,
        torch.ops.aten.bitwise_or.Tensor,
        torch.ops.aten.bitwise_or.Scalar,
        torch.ops.aten.bitwise_or_.Tensor,
        torch.ops.aten.bitwise_or_,
        torch.ops.aten.bitwise_or,
    ).inplace(
        torch.ops.aten.bitwise_or_.Tensor,
        torch.ops.aten.bitwise_or_,
    ).build()
    registry.register_binary("bitwise_xor").targets(
        operator.xor,
        torch.bitwise_xor,
        torch.ops.aten.bitwise_xor.Tensor,
        torch.ops.aten.bitwise_xor.Scalar,
        torch.ops.aten.bitwise_xor_.Tensor,
        torch.ops.aten.bitwise_xor_,
        torch.ops.aten.bitwise_xor,
    ).inplace(
        torch.ops.aten.bitwise_xor_.Tensor,
        torch.ops.aten.bitwise_xor_,
    ).build()
    registry.register_binary("logical_or").targets(
        torch.logical_or,
        torch.ops.aten.logical_or.default,
        torch.ops.aten.logical_or,
        torch.ops.aten.logical_or_.default,
        torch.ops.aten.logical_or_,
    ).inplace(
        torch.ops.aten.logical_or_.default,
        torch.ops.aten.logical_or_,
    ).build()
    registry.register_binary("logical_and").targets(
        torch.logical_and,
        torch.ops.aten.logical_and.default,
        torch.ops.aten.logical_and,
        torch.ops.aten.logical_and_.default,
        torch.ops.aten.logical_and_,
    ).inplace(
        torch.ops.aten.logical_and_.default,
        torch.ops.aten.logical_and_,
    ).build()
    registry.register_binary("logical_xor").targets(
        torch.logical_xor,
        torch.ops.aten.logical_xor.default,
        torch.ops.aten.logical_xor,
        torch.ops.aten.logical_xor_.default,
        torch.ops.aten.logical_xor_,
    ).inplace(
        torch.ops.aten.logical_xor_.default,
        torch.ops.aten.logical_xor_,
    ).build()
    registry.register_unary("logical_not").targets(
        torch.logical_not,
        torch.ops.aten.logical_not.default,
        torch.ops.aten.logical_not,
        torch.ops.aten.logical_not_.default,
        torch.ops.aten.logical_not_,
    ).inplace(
        torch.ops.aten.logical_not_.default,
        torch.ops.aten.logical_not_,
    ).build()
    registry.register_binary("bitwise_left_shift").targets(
        operator.lshift,
        torch.bitwise_left_shift,
        torch.ops.aten.bitwise_left_shift.Tensor,
        torch.ops.aten.bitwise_left_shift_.Tensor,
        torch.ops.aten.bitwise_left_shift_,
        torch.ops.aten.bitwise_left_shift,
    ).inplace(
        torch.ops.aten.bitwise_left_shift_.Tensor,
        torch.ops.aten.bitwise_left_shift_,
    ).build()
    registry.register_binary("bitwise_right_shift").targets(
        operator.rshift,
        torch.bitwise_right_shift,
        torch.ops.aten.bitwise_right_shift.Tensor,
        torch.ops.aten.bitwise_right_shift_.Tensor,
        torch.ops.aten.bitwise_right_shift_,
        torch.ops.aten.bitwise_right_shift,
    ).inplace(
        torch.ops.aten.bitwise_right_shift_.Tensor,
        torch.ops.aten.bitwise_right_shift_,
    ).build()
    registry.register_unary("bitwise_not").targets(
        operator.invert,
        torch.bitwise_not,
        torch.ops.aten.bitwise_not.default,
        torch.ops.aten.bitwise_not,
        torch.ops.aten.bitwise_not_.default,
        torch.ops.aten.bitwise_not_,
    ).inplace(
        torch.ops.aten.bitwise_not_.default,
        torch.ops.aten.bitwise_not_,
    ).build()
    registry.register_binary("div", symbol="/").targets(
        operator.truediv,
        torch.div,
        torch.true_divide,
        torch.ops.aten.div.Tensor,
        torch.ops.aten.div.Scalar,
        torch.ops.aten.div.Tensor_mode,
        torch.ops.aten.div.Scalar_mode,
        torch.ops.aten.div,
        torch.ops.aten.div_.Tensor,
        torch.ops.aten.div_,
    ).inplace(
        torch.ops.aten.div_.Tensor,
        torch.ops.aten.div_,
    ).build()
    registry.register_binary("lt").targets(
        operator.lt,
        torch.lt,
        torch.ops.aten.lt.Tensor,
        torch.ops.aten.lt.Scalar,
        torch.ops.aten.lt.default,
        torch.ops.aten.lt,
    ).build()
    registry.register_binary("le").targets(
        operator.le,
        torch.le,
        torch.ops.aten.le.Tensor,
        torch.ops.aten.le.Scalar,
        torch.ops.aten.le.default,
        torch.ops.aten.le,
    ).build()
    registry.register_binary("gt").targets(
        operator.gt,
        torch.gt,
        torch.ops.aten.gt.Tensor,
        torch.ops.aten.gt.Scalar,
        torch.ops.aten.gt.default,
        torch.ops.aten.gt,
    ).build()
    registry.register_binary("ge").targets(
        operator.ge,
        torch.ge,
        torch.ops.aten.ge.Tensor,
        torch.ops.aten.ge.Scalar,
        torch.ops.aten.ge.default,
        torch.ops.aten.ge,
    ).build()
    registry.register_binary("eq").targets(
        operator.eq,
        torch.eq,
        torch.ops.aten.eq.Tensor,
        torch.ops.aten.eq.Scalar,
        torch.ops.aten.eq.default,
        torch.ops.aten.eq,
    ).build()
    registry.register_binary("ne").targets(
        operator.ne,
        torch.ne,
        torch.ops.aten.ne.Tensor,
        torch.ops.aten.ne.Scalar,
        torch.ops.aten.ne.default,
        torch.ops.aten.ne,
    ).build()
    registry.register_binary("maximum").targets(
        torch.maximum,
        torch.ops.aten.maximum.default,
        torch.ops.aten.maximum,
    ).build()
    registry.register_binary("minimum").targets(
        torch.minimum,
        torch.ops.aten.minimum.default,
        torch.ops.aten.minimum,
    ).build()
    registry.register_binary("atan2").targets(
        torch.atan2,
        torch.ops.aten.atan2.default,
        torch.ops.aten.atan2,
        torch.ops.aten.atan2_.default,
        torch.ops.aten.atan2_,
    ).inplace(
        torch.ops.aten.atan2_.default,
        torch.ops.aten.atan2_,
    ).build()
    registry.register_binary("pow").targets(
        operator.pow,
        torch.pow,
        torch.ops.aten.pow.Tensor_Tensor,
        torch.ops.aten.pow.Tensor_Scalar,
        torch.ops.aten.pow.Scalar,
        torch.ops.aten.pow_.Tensor,
        torch.ops.aten.pow_.Scalar,
        torch.ops.aten.pow_,
    ).inplace(
        torch.ops.aten.pow_.Tensor,
        torch.ops.aten.pow_.Scalar,
        torch.ops.aten.pow_,
    ).build()
    registry.register_binary("remainder").targets(
        torch.remainder,
        torch.ops.aten.remainder.Tensor,
        torch.ops.aten.remainder.Scalar,
        torch.ops.aten.remainder,
        torch.ops.aten.remainder_.Tensor,
        torch.ops.aten.remainder_,
    ).inplace(
        torch.ops.aten.remainder_.Tensor,
        torch.ops.aten.remainder_,
    ).build()
    registry.register_binary("fmod").targets(
        torch.fmod,
        torch.ops.aten.fmod.Tensor,
        torch.ops.aten.fmod.Scalar,
        torch.ops.aten.fmod,
        torch.ops.aten.fmod_.Tensor,
        torch.ops.aten.fmod_,
    ).inplace(
        torch.ops.aten.fmod_.Tensor,
        torch.ops.aten.fmod_,
    ).build()
    registry.register_binary("floor_divide").targets(
        torch.floor_divide,
        torch.ops.aten.floor_divide.default,
        torch.ops.aten.floor_divide.Scalar,
        torch.ops.aten.floor_divide,
        torch.ops.aten.floor_divide_.Tensor,
        torch.ops.aten.floor_divide_,
    ).inplace(
        torch.ops.aten.floor_divide_.Tensor,
        torch.ops.aten.floor_divide_,
    ).build()
    registry.register_binary("fmax").targets(
        torch.fmax,
        torch.ops.aten.fmax.default,
        torch.ops.aten.fmax,
    ).build()
    registry.register_binary("fmin").targets(
        torch.fmin,
        torch.ops.aten.fmin.default,
        torch.ops.aten.fmin,
    ).build()
    registry.register_binary("copysign").targets(
        torch.copysign,
        torch.ops.aten.copysign.default,
        torch.ops.aten.copysign.Tensor,
        torch.ops.aten.copysign.Scalar,
        torch.ops.aten.copysign,
        torch.ops.aten.copysign_.Tensor,
        torch.ops.aten.copysign_,
    ).inplace(
        torch.ops.aten.copysign_.Tensor,
        torch.ops.aten.copysign_,
    ).build()
    registry.register_binary("hypot").targets(
        torch.hypot,
        torch.ops.aten.hypot.default,
        torch.ops.aten.hypot,
        torch.ops.aten.hypot_.default,
        torch.ops.aten.hypot_,
    ).inplace(
        torch.ops.aten.hypot_.default,
        torch.ops.aten.hypot_,
    ).build()
    registry.register_binary("logaddexp").targets(
        torch.logaddexp,
        torch.ops.aten.logaddexp.default,
        torch.ops.aten.logaddexp,
    ).build()
    registry.register_binary("logaddexp2").targets(
        torch.logaddexp2,
        torch.ops.aten.logaddexp2.default,
        torch.ops.aten.logaddexp2,
    ).build()
    registry.register_binary("nextafter").targets(
        torch.nextafter,
        torch.ops.aten.nextafter.default,
        torch.ops.aten.nextafter,
        torch.ops.aten.nextafter_.default,
        torch.ops.aten.nextafter_,
    ).inplace(
        torch.ops.aten.nextafter_.default,
        torch.ops.aten.nextafter_,
    ).build()
    registry.register_binary("xlogy").targets(
        torch.xlogy,
        torch.ops.aten.xlogy.Tensor,
        torch.ops.aten.xlogy,
        torch.ops.aten.xlogy_.Tensor,
        torch.ops.aten.xlogy_,
    ).inplace(
        torch.ops.aten.xlogy_.Tensor,
        torch.ops.aten.xlogy_,
    ).build()
    registry.register_binary("heaviside").targets(
        torch.heaviside,
        torch.ops.aten.heaviside.default,
        torch.ops.aten.heaviside,
        torch.ops.aten.heaviside_.default,
        torch.ops.aten.heaviside_,
    ).inplace(
        torch.ops.aten.heaviside_.default,
        torch.ops.aten.heaviside_,
    ).build()
    registry.register_op("where", kind=OpKind.WHERE).targets(
        torch.where,
        torch.ops.aten.where.self,
        torch.ops.aten.where.Scalar,
    ).build()
    registry.register_binary("ldexp").targets(
        torch.ldexp,
        torch.ops.aten.ldexp.default,
        torch.ops.aten.ldexp,
        torch.ops.aten.ldexp_.default,
        torch.ops.aten.ldexp_,
    ).inplace(
        torch.ops.aten.ldexp_.default,
        torch.ops.aten.ldexp_,
    ).build()
    registry.register_binary("clamp_min").targets(
        torch.clamp_min,
        torch.ops.aten.clamp_min.Tensor,
        torch.ops.aten.clamp_min.default,
        torch.ops.aten.clamp_min,
        torch.ops.aten.clamp_min_.default,
        torch.ops.aten.clamp_min_.Tensor,
        torch.ops.aten.clamp_min_,
    ).inplace(
        torch.ops.aten.clamp_min_.default,
        torch.ops.aten.clamp_min_.Tensor,
        torch.ops.aten.clamp_min_,
    ).build()
    registry.register_binary("clamp_max").targets(
        torch.clamp_max,
        torch.ops.aten.clamp_max.Tensor,
        torch.ops.aten.clamp_max.default,
        torch.ops.aten.clamp_max,
        torch.ops.aten.clamp_max_.default,
        torch.ops.aten.clamp_max_.Tensor,
        torch.ops.aten.clamp_max_,
    ).inplace(
        torch.ops.aten.clamp_max_.default,
        torch.ops.aten.clamp_max_.Tensor,
        torch.ops.aten.clamp_max_,
    ).build()
    registry.register_binary("clamp_tensor").targets(
        torch.ops.aten.clamp.Tensor,
        torch.ops.aten.clamp_.Tensor,
    ).inplace(
        torch.ops.aten.clamp_.Tensor,
    ).build()
    registry.register_unary("clamp").targets(
        torch.clamp,
        torch.ops.aten.clamp.default,
        torch.ops.aten.clamp,
        torch.ops.aten.clamp_.default,
        torch.ops.aten.clamp_,
    ).inplace(
        torch.ops.aten.clamp_.default,
        torch.ops.aten.clamp_,
    ).build()
    registry.register_unary("neg").targets(
        operator.neg,
        torch.neg,
        torch.ops.aten.neg.default,
        torch.ops.aten.neg,
        torch.ops.aten.neg_.default,
        torch.ops.aten.neg_,
    ).inplace(
        torch.ops.aten.neg_.default,
        torch.ops.aten.neg_,
    ).build()
    registry.register_unary("exp").targets(
        torch.exp,
        torch.ops.aten.exp.default,
        torch.ops.aten.exp,
        torch.ops.aten.exp_.default,
        torch.ops.aten.exp_,
    ).inplace(
        torch.ops.aten.exp_.default,
        torch.ops.aten.exp_,
    ).build()
    registry.register_unary("abs").targets(
        torch.abs,
        torch.ops.aten.abs.default,
        torch.ops.aten.abs,
        torch.ops.aten.abs_.default,
        torch.ops.aten.abs_,
    ).inplace(
        torch.ops.aten.abs_.default,
        torch.ops.aten.abs_,
    ).build()
    registry.register_unary("absolute").targets(
        torch.absolute,
        torch.ops.aten.absolute.default,
        torch.ops.aten.absolute,
        torch.ops.aten.absolute_.default,
        torch.ops.aten.absolute_,
    ).inplace(
        torch.ops.aten.absolute_.default,
        torch.ops.aten.absolute_,
    ).build()
    registry.register_unary("sqrt").targets(
        torch.sqrt,
        torch.ops.aten.sqrt.default,
        torch.ops.aten.sqrt,
        torch.ops.aten.sqrt_.default,
        torch.ops.aten.sqrt_,
    ).inplace(
        torch.ops.aten.sqrt_.default,
        torch.ops.aten.sqrt_,
    ).build()
    _cbrt_targets = []
    cbrt_op = getattr(torch, "cbrt", None)
    if cbrt_op is not None:
        _cbrt_targets.append(cbrt_op)
    aten_cbrt = getattr(torch.ops.aten, "cbrt", None)
    if aten_cbrt is not None:
        _cbrt_targets.extend([aten_cbrt.default, aten_cbrt])
    aten_cbrt_inplace = getattr(torch.ops.aten, "cbrt_", None)
    _cbrt_inplace_targets = []
    if aten_cbrt_inplace is not None:
        _cbrt_inplace_targets.extend(
            [aten_cbrt_inplace.default, aten_cbrt_inplace]
        )
    if _cbrt_targets:
        registry.register_unary("cbrt").targets(_cbrt_targets).inplace(
            _cbrt_inplace_targets
        ).build()
    registry.register_unary("log").targets(
        torch.log,
        torch.ops.aten.log.default,
        torch.ops.aten.log,
        torch.ops.aten.log_.default,
        torch.ops.aten.log_,
    ).inplace(
        torch.ops.aten.log_.default,
        torch.ops.aten.log_,
    ).build()
    registry.register_unary("sin").targets(
        torch.sin,
        torch.ops.aten.sin.default,
        torch.ops.aten.sin,
        torch.ops.aten.sin_.default,
        torch.ops.aten.sin_,
    ).inplace(
        torch.ops.aten.sin_.default,
        torch.ops.aten.sin_,
    ).build()
    registry.register_unary("cos").targets(
        torch.cos,
        torch.ops.aten.cos.default,
        torch.ops.aten.cos,
        torch.ops.aten.cos_.default,
        torch.ops.aten.cos_,
    ).inplace(
        torch.ops.aten.cos_.default,
        torch.ops.aten.cos_,
    ).build()
    registry.register_unary("acos").targets(
        torch.acos,
        torch.ops.aten.acos.default,
        torch.ops.aten.acos,
        torch.ops.aten.acos_.default,
        torch.ops.aten.acos_,
    ).inplace(
        torch.ops.aten.acos_.default,
        torch.ops.aten.acos_,
    ).build()
    registry.register_unary("arccos").targets(
        torch.arccos,
        torch.ops.aten.arccos.default,
        torch.ops.aten.arccos,
        torch.ops.aten.arccos_.default,
        torch.ops.aten.arccos_,
    ).inplace(
        torch.ops.aten.arccos_.default,
        torch.ops.aten.arccos_,
    ).build()
    registry.register_unary("acosh").targets(
        torch.acosh,
        torch.arccosh,
        torch.ops.aten.acosh.default,
        torch.ops.aten.acosh,
        torch.ops.aten.acosh_.default,
        torch.ops.aten.acosh_,
        torch.ops.aten.arccosh.default,
        torch.ops.aten.arccosh,
        torch.ops.aten.arccosh_.default,
        torch.ops.aten.arccosh_,
    ).inplace(
        torch.ops.aten.acosh_.default,
        torch.ops.aten.acosh_,
        torch.ops.aten.arccosh_.default,
        torch.ops.aten.arccosh_,
    ).build()
    registry.register_unary("asin").targets(
        torch.asin,
        torch.ops.aten.asin.default,
        torch.ops.aten.asin,
        torch.ops.aten.asin_.default,
        torch.ops.aten.asin_,
    ).inplace(
        torch.ops.aten.asin_.default,
        torch.ops.aten.asin_,
    ).build()
    registry.register_unary("arcsin").targets(
        torch.arcsin,
        torch.ops.aten.arcsin.default,
        torch.ops.aten.arcsin,
        torch.ops.aten.arcsin_.default,
        torch.ops.aten.arcsin_,
    ).inplace(
        torch.ops.aten.arcsin_.default,
        torch.ops.aten.arcsin_,
    ).build()
    registry.register_unary("asinh").targets(
        torch.asinh,
        torch.ops.aten.asinh.default,
        torch.ops.aten.asinh,
        torch.ops.aten.asinh_.default,
        torch.ops.aten.asinh_,
    ).inplace(
        torch.ops.aten.asinh_.default,
        torch.ops.aten.asinh_,
    ).build()
    registry.register_unary("arcsinh").targets(
        torch.arcsinh,
        torch.ops.aten.arcsinh.default,
        torch.ops.aten.arcsinh,
        torch.ops.aten.arcsinh_.default,
        torch.ops.aten.arcsinh_,
    ).inplace(
        torch.ops.aten.arcsinh_.default,
        torch.ops.aten.arcsinh_,
    ).build()
    registry.register_unary("atan").targets(
        torch.atan,
        torch.ops.aten.atan.default,
        torch.ops.aten.atan,
        torch.ops.aten.atan_.default,
        torch.ops.aten.atan_,
    ).inplace(
        torch.ops.aten.atan_.default,
        torch.ops.aten.atan_,
    ).build()
    registry.register_unary("arctan").targets(
        torch.arctan,
        torch.ops.aten.arctan.default,
        torch.ops.aten.arctan,
        torch.ops.aten.arctan_.default,
        torch.ops.aten.arctan_,
    ).inplace(
        torch.ops.aten.arctan_.default,
        torch.ops.aten.arctan_,
    ).build()
    registry.register_unary("atanh").targets(
        torch.atanh,
        torch.ops.aten.atanh.default,
        torch.ops.aten.atanh,
        torch.ops.aten.atanh_.default,
        torch.ops.aten.atanh_,
    ).inplace(
        torch.ops.aten.atanh_.default,
        torch.ops.aten.atanh_,
    ).build()
    registry.register_unary("cosh").targets(
        torch.cosh,
        torch.ops.aten.cosh.default,
        torch.ops.aten.cosh,
        torch.ops.aten.cosh_.default,
        torch.ops.aten.cosh_,
    ).inplace(
        torch.ops.aten.cosh_.default,
        torch.ops.aten.cosh_,
    ).build()
    registry.register_unary("sinh").targets(
        torch.sinh,
        torch.ops.aten.sinh.default,
        torch.ops.aten.sinh,
        torch.ops.aten.sinh_.default,
        torch.ops.aten.sinh_,
    ).inplace(
        torch.ops.aten.sinh_.default,
        torch.ops.aten.sinh_,
    ).build()
    registry.register_unary("tan").targets(
        torch.tan,
        torch.ops.aten.tan.default,
        torch.ops.aten.tan,
        torch.ops.aten.tan_.default,
        torch.ops.aten.tan_,
    ).inplace(
        torch.ops.aten.tan_.default,
        torch.ops.aten.tan_,
    ).build()
    registry.register_unary("erf").targets(
        torch.erf,
        torch.ops.aten.erf.default,
        torch.ops.aten.erf,
        torch.ops.aten.erf_.default,
        torch.ops.aten.erf_,
    ).inplace(
        torch.ops.aten.erf_.default,
        torch.ops.aten.erf_,
    ).build()
    registry.register_unary("erfc").targets(
        torch.erfc,
        torch.ops.aten.erfc.default,
        torch.ops.aten.erfc,
        torch.ops.aten.erfc_.default,
        torch.ops.aten.erfc_,
    ).inplace(
        torch.ops.aten.erfc_.default,
        torch.ops.aten.erfc_,
    ).build()
    registry.register_unary("expm1").targets(
        torch.expm1,
        torch.ops.aten.expm1.default,
        torch.ops.aten.expm1,
        torch.ops.aten.expm1_.default,
        torch.ops.aten.expm1_,
    ).inplace(
        torch.ops.aten.expm1_.default,
        torch.ops.aten.expm1_,
    ).build()
    registry.register_unary("log1p").targets(
        torch.log1p,
        torch.ops.aten.log1p.default,
        torch.ops.aten.log1p,
        torch.ops.aten.log1p_.default,
        torch.ops.aten.log1p_,
    ).inplace(
        torch.ops.aten.log1p_.default,
        torch.ops.aten.log1p_,
    ).build()
    registry.register_unary("log2").targets(
        torch.log2,
        torch.ops.aten.log2.default,
        torch.ops.aten.log2,
        torch.ops.aten.log2_.default,
        torch.ops.aten.log2_,
    ).inplace(
        torch.ops.aten.log2_.default,
        torch.ops.aten.log2_,
    ).build()
    registry.register_unary("log10").targets(
        torch.log10,
        torch.ops.aten.log10.default,
        torch.ops.aten.log10,
        torch.ops.aten.log10_.default,
        torch.ops.aten.log10_,
    ).inplace(
        torch.ops.aten.log10_.default,
        torch.ops.aten.log10_,
    ).build()
    registry.register_unary("rsqrt").targets(
        torch.rsqrt,
        torch.ops.aten.rsqrt.default,
        torch.ops.aten.rsqrt,
        torch.ops.aten.rsqrt_.default,
        torch.ops.aten.rsqrt_,
    ).inplace(
        torch.ops.aten.rsqrt_.default,
        torch.ops.aten.rsqrt_,
    ).build()
    registry.register_unary("sigmoid").targets(
        torch.sigmoid,
        torch.ops.aten.sigmoid.default,
        torch.ops.aten.sigmoid,
        torch.ops.aten.sigmoid_.default,
        torch.ops.aten.sigmoid_,
    ).inplace(
        torch.ops.aten.sigmoid_.default,
        torch.ops.aten.sigmoid_,
    ).build()
    registry.register_unary("log_sigmoid").targets(
        F.logsigmoid,
        torch.ops.aten.log_sigmoid.default,
        torch.ops.aten.log_sigmoid,
    ).build()
    registry.register_unary("gelu").targets(
        F.gelu,
        torch.ops.aten.gelu.default,
        torch.ops.aten.gelu,
        torch.ops.aten.gelu_.default,
        torch.ops.aten.gelu_,
    ).inplace(
        torch.ops.aten.gelu_.default,
        torch.ops.aten.gelu_,
    ).build()
    registry.register_unary("elu").targets(
        F.elu,
        torch.ops.aten.elu.default,
        torch.ops.aten.elu,
        torch.ops.aten.elu_.default,
        torch.ops.aten.elu_,
    ).inplace(
        torch.ops.aten.elu_.default,
        torch.ops.aten.elu_,
    ).build()
    registry.register_unary("leaky_relu").targets(
        F.leaky_relu,
        torch.ops.aten.leaky_relu.default,
        torch.ops.aten.leaky_relu,
        torch.ops.aten.leaky_relu_.default,
        torch.ops.aten.leaky_relu_,
    ).inplace(
        torch.ops.aten.leaky_relu_.default,
        torch.ops.aten.leaky_relu_,
    ).build()
    registry.register_unary("softplus").targets(
        F.softplus,
        torch.ops.aten.softplus.default,
        torch.ops.aten.softplus,
    ).build()
    registry.register_unary("selu").targets(
        F.selu,
        torch.ops.aten.selu.default,
        torch.ops.aten.selu,
        torch.ops.aten.selu_.default,
        torch.ops.aten.selu_,
    ).inplace(
        torch.ops.aten.selu_.default,
        torch.ops.aten.selu_,
    ).build()
    registry.register_unary("relu6").targets(
        F.relu6,
        torch.ops.aten.relu6.default,
        torch.ops.aten.relu6,
    ).build()
    registry.register_unary("hardsigmoid").targets(
        F.hardsigmoid,
        torch.ops.aten.hardsigmoid.default,
        torch.ops.aten.hardsigmoid,
    ).build()
    registry.register_unary("hardtanh").targets(
        F.hardtanh,
        torch.ops.aten.hardtanh.default,
        torch.ops.aten.hardtanh,
        torch.ops.aten.hardtanh_.default,
        torch.ops.aten.hardtanh_,
    ).inplace(
        torch.ops.aten.hardtanh_.default,
        torch.ops.aten.hardtanh_,
    ).build()
    registry.register_unary("mish").targets(
        F.mish,
        torch.ops.aten.mish.default,
        torch.ops.aten.mish,
        torch.ops.aten.mish_.default,
        torch.ops.aten.mish_,
    ).inplace(
        torch.ops.aten.mish_.default,
        torch.ops.aten.mish_,
    ).build()
    registry.register_unary("silu").targets(
        F.silu,
        torch.ops.aten.silu.default,
        torch.ops.aten.silu,
        torch.ops.aten.silu_.default,
        torch.ops.aten.silu_,
    ).inplace(
        torch.ops.aten.silu_.default,
        torch.ops.aten.silu_,
    ).build()
    registry.register_unary("hardswish").targets(
        F.hardswish,
        torch.ops.aten.hardswish.default,
        torch.ops.aten.hardswish,
        torch.ops.aten.hardswish_.default,
        torch.ops.aten.hardswish_,
    ).inplace(
        torch.ops.aten.hardswish_.default,
        torch.ops.aten.hardswish_,
    ).build()
    registry.register_unary("sign").targets(
        torch.sign,
        torch.ops.aten.sign.default,
        torch.ops.aten.sign,
        torch.ops.aten.sign_.default,
        torch.ops.aten.sign_,
    ).inplace(
        torch.ops.aten.sign_.default,
        torch.ops.aten.sign_,
    ).build()
    registry.register_unary("round").targets(
        torch.round,
        torch.ops.aten.round.default,
        torch.ops.aten.round,
        torch.ops.aten.round_.default,
        torch.ops.aten.round_,
    ).inplace(
        torch.ops.aten.round_.default,
        torch.ops.aten.round_,
    ).build()
    registry.register_unary("trunc").targets(
        torch.trunc,
        torch.ops.aten.trunc.default,
        torch.ops.aten.trunc,
        torch.ops.aten.trunc_.default,
        torch.ops.aten.trunc_,
    ).inplace(
        torch.ops.aten.trunc_.default,
        torch.ops.aten.trunc_,
    ).build()
    registry.register_unary("tanh").targets(
        torch.tanh,
        torch.ops.aten.tanh.default,
        torch.ops.aten.tanh,
        torch.ops.aten.tanh_.default,
        torch.ops.aten.tanh_,
    ).inplace(
        torch.ops.aten.tanh_.default,
        torch.ops.aten.tanh_,
    ).build()
    registry.register_unary("floor").targets(
        torch.floor,
        torch.ops.aten.floor.default,
        torch.ops.aten.floor,
        torch.ops.aten.floor_.default,
        torch.ops.aten.floor_,
    ).inplace(
        torch.ops.aten.floor_.default,
        torch.ops.aten.floor_,
    ).build()
    registry.register_unary("ceil").targets(
        torch.ceil,
        torch.ops.aten.ceil.default,
        torch.ops.aten.ceil,
        torch.ops.aten.ceil_.default,
        torch.ops.aten.ceil_,
    ).inplace(
        torch.ops.aten.ceil_.default,
        torch.ops.aten.ceil_,
    ).build()
    registry.register_unary("reciprocal").targets(
        torch.reciprocal,
        torch.ops.aten.reciprocal.default,
        torch.ops.aten.reciprocal,
        torch.ops.aten.reciprocal_.default,
        torch.ops.aten.reciprocal_,
    ).inplace(
        torch.ops.aten.reciprocal_.default,
        torch.ops.aten.reciprocal_,
    ).build()
    registry.register_unary("relu").targets(
        F.relu,
        torch.relu,
        torch.ops.aten.relu.default,
        torch.ops.aten.relu,
        torch.ops.aten.relu_.default,
        torch.ops.aten.relu_,
    ).inplace(
        torch.ops.aten.relu_.default,
        torch.ops.aten.relu_,
    ).build()
    registry.register_unary("angle").targets(
        torch.angle,
        torch.ops.aten.angle.default,
        torch.ops.aten.angle,
    ).build()
    registry.register_unary("conj").targets(
        torch.conj,
        torch.ops.aten.conj.default,
        torch.ops.aten.conj,
    ).build()
    registry.register_unary("conj_physical").targets(
        torch.conj_physical,
        torch.ops.aten.conj_physical.default,
        torch.ops.aten.conj_physical,
        torch.ops.aten.conj_physical_.default,
        torch.ops.aten.conj_physical_,
    ).inplace(
        torch.ops.aten.conj_physical_.default,
        torch.ops.aten.conj_physical_,
    ).build()
    registry.register_unary("clone").targets(
        torch.clone,
        torch.ops.aten.clone.default,
        torch.ops.aten.clone,
    ).build()
    registry.register_unary("alias").targets(
        torch.ops.aten.alias.default,
        torch.ops.aten.alias,
    ).build()
    registry.register_binary("copy").targets(
        torch.ops.aten.copy.default,
        torch.ops.aten.copy,
    ).build()
    registry.register_op("fill", OpKind.FILL).targets(
        torch.ops.aten.fill.Scalar,
        torch.ops.aten.fill,
        torch.ops.aten.fill_.Scalar,
        torch.ops.aten.fill_,
    ).inplace(
        torch.ops.aten.fill_.Scalar,
        torch.ops.aten.fill_,
        arg_index=0,
    ).build()
    registry.register_op("full_like", OpKind.FILL).targets(
        torch.ops.aten.full_like.default,
        torch.ops.aten.full_like,
    ).build()
    registry.register_unary("deg2rad").targets(
        torch.deg2rad,
        torch.ops.aten.deg2rad.default,
        torch.ops.aten.deg2rad,
        torch.ops.aten.deg2rad_.default,
        torch.ops.aten.deg2rad_,
    ).inplace(
        torch.ops.aten.deg2rad_.default,
        torch.ops.aten.deg2rad_,
    ).build()
    registry.register_unary("digamma").targets(
        torch.digamma,
        torch.ops.aten.digamma.default,
        torch.ops.aten.digamma,
        torch.ops.aten.digamma_.default,
        torch.ops.aten.digamma_,
    ).inplace(
        torch.ops.aten.digamma_.default,
        torch.ops.aten.digamma_,
    ).build()
    registry.register_unary("erfinv").targets(
        torch.erfinv,
        torch.ops.aten.erfinv.default,
        torch.ops.aten.erfinv,
        torch.ops.aten.erfinv_.default,
        torch.ops.aten.erfinv_,
    ).inplace(
        torch.ops.aten.erfinv_.default,
        torch.ops.aten.erfinv_,
    ).build()
    registry.register_unary("exp2").targets(
        torch.exp2,
        torch.ops.aten.exp2.default,
        torch.ops.aten.exp2,
        torch.ops.aten.exp2_.default,
        torch.ops.aten.exp2_,
    ).inplace(
        torch.ops.aten.exp2_.default,
        torch.ops.aten.exp2_,
    ).build()
    registry.register_unary("frac").targets(
        torch.frac,
        torch.ops.aten.frac.default,
        torch.ops.aten.frac,
        torch.ops.aten.frac_.default,
        torch.ops.aten.frac_,
    ).inplace(
        torch.ops.aten.frac_.default,
        torch.ops.aten.frac_,
    ).build()
    registry.register_unary("i0").targets(
        torch.i0,
        torch.ops.aten.i0.default,
        torch.ops.aten.i0,
        torch.ops.aten.i0_.default,
        torch.ops.aten.i0_,
    ).inplace(
        torch.ops.aten.i0_.default,
        torch.ops.aten.i0_,
    ).build()
    registry.register_unary("isfinite").targets(
        torch.isfinite,
        torch.ops.aten.isfinite.default,
        torch.ops.aten.isfinite,
    ).build()
    registry.register_unary("isinf").targets(
        torch.isinf,
        torch.ops.aten.isinf.default,
        torch.ops.aten.isinf,
    ).build()
    registry.register_unary("isnan").targets(
        torch.isnan,
        torch.ops.aten.isnan.default,
        torch.ops.aten.isnan,
    ).build()
    registry.register_unary("isneginf").targets(
        torch.isneginf,
        torch.ops.aten.isneginf.default,
        torch.ops.aten.isneginf,
    ).build()
    registry.register_unary("isposinf").targets(
        torch.isposinf,
        torch.ops.aten.isposinf.default,
        torch.ops.aten.isposinf,
    ).build()
    registry.register_unary("lgamma").targets(
        torch.lgamma,
        torch.ops.aten.lgamma.default,
        torch.ops.aten.lgamma,
        torch.ops.aten.lgamma_.default,
        torch.ops.aten.lgamma_,
    ).inplace(
        torch.ops.aten.lgamma_.default,
        torch.ops.aten.lgamma_,
    ).build()
    registry.register_unary("logit").targets(
        torch.logit,
        torch.ops.aten.logit.default,
        torch.ops.aten.logit,
        torch.ops.aten.logit_.default,
        torch.ops.aten.logit_,
    ).inplace(
        torch.ops.aten.logit_.default,
        torch.ops.aten.logit_,
    ).build()
    registry.register_unary("nan_to_num").targets(
        torch.nan_to_num,
        torch.ops.aten.nan_to_num.default,
        torch.ops.aten.nan_to_num,
        torch.ops.aten.nan_to_num_.default,
        torch.ops.aten.nan_to_num_,
    ).inplace(
        torch.ops.aten.nan_to_num_.default,
        torch.ops.aten.nan_to_num_,
    ).build()
    registry.register_unary("positive").targets(
        torch.positive,
        torch.ops.aten.positive.default,
        torch.ops.aten.positive,
    ).build()
    registry.register_unary("rad2deg").targets(
        torch.rad2deg,
        torch.ops.aten.rad2deg.default,
        torch.ops.aten.rad2deg,
        torch.ops.aten.rad2deg_.default,
        torch.ops.aten.rad2deg_,
    ).inplace(
        torch.ops.aten.rad2deg_.default,
        torch.ops.aten.rad2deg_,
    ).build()
    registry.register_unary("real").targets(
        torch.real,
        torch.ops.aten.real.default,
        torch.ops.aten.real,
    ).build()
    registry.register_unary("sgn").targets(
        torch.sgn,
        torch.ops.aten.sgn.default,
        torch.ops.aten.sgn,
        torch.ops.aten.sgn_.default,
        torch.ops.aten.sgn_,
    ).inplace(
        torch.ops.aten.sgn_.default,
        torch.ops.aten.sgn_,
    ).build()
    registry.register_unary("sinc").targets(
        torch.sinc,
        torch.ops.aten.sinc.default,
        torch.ops.aten.sinc,
        torch.ops.aten.sinc_.default,
        torch.ops.aten.sinc_,
    ).inplace(
        torch.ops.aten.sinc_.default,
        torch.ops.aten.sinc_,
    ).build()
    registry.register_unary("square").targets(
        torch.square,
        torch.ops.aten.square.default,
        torch.ops.aten.square,
        torch.ops.aten.square_.default,
        torch.ops.aten.square_,
    ).inplace(
        torch.ops.aten.square_.default,
        torch.ops.aten.square_,
    ).build()

    return registry.build()


def build_target_registry(
    supported_ops: dict[str, _OpSpec],
) -> dict[object, _TargetInfo]:
    registry = _base_target_registry(supported_ops)
    if "atan2" in supported_ops:
        registry[torch.ops.aten.atan2.out] = _TargetInfo(
            op_spec=supported_ops["atan2"],
            inplace_arg_index=2,
        )
    return registry


__all__ = ["build_supported_ops", "build_target_registry"]
