/*
 * Generated by emx-pytorch2c export_generic_c.
 * Options:
 *   function_name: 'entry'
 *   truncate_weights_after: 10
 *   temp_allocation_threshold: 1024
 *   variable_dim_inputs: {}
 *   variable_dim_outputs: {}
 */
#include <stdint.h>
#include <sys/types.h>
#include <stdbool.h>


/*
* op: clone (kind: unary)
* inputs: [shape=(1, 3), size=3]
* output: shape=(1, 3), size=3
* params: {}
*/
void node1_clone_f32(const float a[1][3], float out[1][3]) {
    for (ssize_t i0 = 0; i0 < 1; ++i0) {
        for (ssize_t i1 = 0; i1 < 3; ++i1) {
            out[i0][i1] = a[i0][i1];
        }
    }
}

void ref_codegen_main_f32(const float input_0[1][3], float out[1][3]) {
    node1_clone_f32(input_0, out);
}

void entry(const float in0[1][3], float out0[1][3]) {
    ref_codegen_main_f32(in0, out0);
}
