/*
 * Generated by emx-pytorch2c export_generic_c.
 * Options:
 *   function_name: 'entry'
 *   truncate_weights_after: 10
 *   temp_allocation_threshold: 1024
 *   variable_dim_inputs: {}
 *   variable_dim_outputs: {}
 */
#include <stdint.h>
#include <sys/types.h>
#include <stdbool.h>
static const float weight_MatMul_my_weight[2][2] = {
    {
        0x1.000000p+0f, 0x0.0p+0f
    },
    {
        0x0.0p+0f, 0x1.000000p+0f
    }
};

#ifndef REF_PI_F
#define REF_PI_F 3.14159265358979323846f
#endif
#ifndef REF_PI_D
#define REF_PI_D 3.14159265358979323846
#endif


/*
* op: linear (kind: linear)
* inputs: [shape=(1, 2), size=2, shape=(2, 2), size=4]
* output: shape=(1, 2), size=2
* params: {'has_bias': False}
*/
void node1_linear_f32(const float input[1][2], const float weight[2][2], float out[1][2]) {
    for (ssize_t i0 = 0; i0 < 1; ++i0) {
        for (ssize_t j = 0; j < 2; ++j) {
            float acc = 0.0f;
            for (ssize_t t = 0; t < 2; ++t) {
                acc += input[i0][t] * ((float*)weight)[j * 1 + t * 2];
            }
            out[i0][j] = acc + 0;
        }
    }
}

void ref_codegen_main_f32(const float input_0[1][2], const float input_1[2][2], float out[1][2]) {
    node1_linear_f32(input_0, input_1, out);
}

void entry(const float in0[1][2], float out0[1][2]) {
    ref_codegen_main_f32(in0, weight_MatMul_my_weight, out0);
}
