/*
 * Generated by emx-pytorch2c export_generic_c.
 * Options:
 *   function_name: 'model_run'
 *   truncate_weights_after: None
 *   temp_allocation_threshold: 1024
 *   variable_dim_inputs: {0: [0]}
 *   variable_dim_outputs: {}
 */
#include <stdint.h>
#include <sys/types.h>
#include <stdbool.h>
#include "ops_scalar_f32.h"

/*
* op: add (kind: binary)
* inputs: [shape=(2, 4), size=8]
* output: shape=(2, 4), size=8
* params: {'scalar': 1}
*/
void node1_add_f32(int dim1, const float a[dim1][4], float out[dim1][4]) {
    for (ssize_t i0 = 0; i0 < dim1; ++i0) {
        for (ssize_t i1 = 0; i1 < 4; ++i1) {
            out[i0][i1] = ref_scalar_f32_add(a[i0][i1], 1.0f);
        }
    }
}

void ref_codegen_main_f32(int dim1, const float input_0[dim1][4], float out[dim1][4]) {
    node1_add_f32(dim1, input_0, out);
}

void model_run(int dim1, const float in0[dim1][4], float out0[dim1][4]) {
    ref_codegen_main_f32(dim1, in0, out0);
}
